#!/bin/bash

PROJECT_DIR="${PWD}"
REAL_HOME="${HOME}"

bwrap \
  --ro-bind /usr /usr \
  --ro-bind /bin /bin \
  --ro-bind /lib /lib \
  --ro-bind /lib64 /lib64 \
  --ro-bind /etc/resolv.conf /etc/resolv.conf \
  --ro-bind /etc/ssl /etc/ssl \
  --ro-bind /etc/ca-certificates /etc/ca-certificates \
  --ro-bind /etc/hosts /etc/hosts \
  --dev /dev \
  --proc /proc \
  --tmpfs /tmp \
  --tmpfs /run \
  --bind "${HOME}/.cache" "${HOME}/.cache" \
  --bind "${HOME}/.local/share/opencode" "${HOME}/.local/share/opencode" \
  --bind "${HOME}/.config/opencode" "${HOME}/.config/opencode" \
  --bind "${PROJECT_DIR}" "${PROJECT_DIR}" \
  --ro-bind "${REAL_HOME}/.config" "${HOME}/.config" \
  --chdir "${PROJECT_DIR}" \
  --unshare-all --share-net \
  --die-with-parent \
  --setenv TERM "${TERM}" \
  --setenv COLORTERM "${COLORTERM:-truecolor}" \
  --setenv PS1 "(jail-opencode) \w \$ " \
  opencode "$@"
